
import type { ExecutiveProfile, StartupNeeds } from './types';

export const allSkills = [
  // Business & Strategy
  'Business Development',
  'Business Strategy',
  'Change Management',
  'Corporate Development',
  'Corporate Strategy',
  'Fundraising',
  'Go-to-Market (GTM) Strategy',
  'International Expansion',
  'Investor Relations',
  'M&A (Mergers & Acquisitions)',
  'Management Consulting',
  'Market Research',
  'Operations Management',
  'Organizational Design',
  'Pricing Strategy',
  'Process Optimization',
  'Strategic Planning',
  'Supply Chain Management',
  'Venture Capital',

  // Marketing & Sales
  'B2B Marketing',
  'B2C Marketing',
  'Brand Management',
  'Brand Strategy',
  'Content Marketing',
  'Demand Generation',
  'Digital Marketing',
  'E-commerce',
  'Enterprise Sales',
  'Growth Hacking',
  'Growth Marketing',
  'Lead Generation',
  'Marketing Analytics',
  'Marketing Automation',
  'Partner Marketing',
  'Product-Led Growth (PLG)',
  'Product Marketing',
  'Public Relations (PR)',
  'Sales Operations',
  'Sales Strategy',
  'SEO/SEM',
  'Social Media Marketing',

  // Finance & Operations
  'Accounting',
  'Budgeting & Forecasting',
  'Capital Raising',
  'Corporate Finance',
  'Financial Modeling',
  'FP&A (Financial Planning & Analysis)',
  'Logistics',
  'Manufacturing',
  'Risk Management',

  // Product & Technology
  'Agile Methodologies',
  'AI/ML (Artificial Intelligence/Machine Learning)',
  'API Design',
  'Big Data',
  'Cloud Architecture',
  'Cloud Infrastructure',
  'Cybersecurity',
  'Data Analytics',
  'Data Engineering',
  'Data Science',
  'DevOps',
  'Enterprise Software',
  'IT Infrastructure',
  'IT Strategy',
  'Kubernetes',
  'Microservices',
  'Mobile Development',
  'Product Management',
  'Product Roadmapping',
  'SaaS (Software as a Service)',
  'Scalable Systems',
  'Software Development',
  'Technical Leadership',
  'UI/UX Design',
  'Web3',

  // People & HR
  'Compensation & Benefits',
  'Culture Building',
  'Diversity & Inclusion (D&I)',
  'Employee Relations',
  'HR Operations',
  'Organizational Development',
  'Performance Management',
  'Talent Acquisition',
  'Team Leadership',

  // Industry Specific
  'AdTech',
  'CleanTech',
  'ClimateTech',
  'Consumer Goods (D2C)',
  'DeepTech',
  'EdTech',
  'Energy',
  'Fintech',
  'GovTech',
  'Hardware',
  'HealthTech',
  'Insurance',
  'LegalTech',
  'Life Sciences',
  'Marketplaces',
  'Media & Entertainment',
  'PropTech',
  'Real Estate',
  'Retail',
  'Robotics',
  'Telecommunications',
  'Transportation',
];
